name: Tenton Uploader

on:
  schedule:
    - cron: "0 5 * * *"   # 毎日14:00 JST（UTCで5:00）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run script
        env:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          TENTON_USER: ${{ secrets.TENTON_USER }}
          TENTON_PASS: ${{ secrets.TENTON_PASS }}
          CHATWORK_TOKEN: ${{ secrets.CHATWORK_TOKEN }}      # ← 追加！
          CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}  # ← 追加！
        run: python main.py

      # ✅ デバッグログ収集（失敗時のみ）
      - name: Upload debug artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            debug*.html
            debug*.png
